from __future__ import annotations

class DNA:
    def __init__(self, seq: str | bytes | bytearray | memoryview | DNA) -> None: ...

    def reverse_complement(self) -> DNA: ...

    def to_bytes(self) -> bytes: ...

    def __len__(self) -> int: ...
    def __bytes__(self) -> bytes: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

    # concatenation
    def __add__(self, other: str | bytes | bytearray | memoryview | DNA) -> DNA: ...
    def __radd__(self, other: str | bytes | bytearray | memoryview | DNA) -> DNA: ...

def complement(a: int) -> int: ...